open-edge-platform/model_api

- model_api/cpp/models/src/detection_model_yolo.cpp
See https://github.com/openvinotoolkit/open_model_zoo/pull/3727
> Fix precision for scale_values

- model_api/cpp/adapters/include/adapters/inference_adapter.h
> Make InferenceAdapter destructor virtual

- model_api/cpp/models/include/models/segmentation_model.h
- model_api/cpp/models/src/segmentation_model.cpp
> Fix SegmentationModel

- examples/cpp/synchronous_api/main.cpp
File utils/color_palette.hpp doesn't exist
> Fix cpp example build

- model_api/python/openvino/model_api/adapters/openvino_adapter.py
Path(<bytes object>) fails, so we should avoid such call
> Prevent failure in OV adapter if model in a binary form was passed

- README.md
- model_api/python/setup.py
It seems there's no way to modify Project description with web UI. So I'm going to publish it one more time.
Test: https://test.pypi.org/project/openvino-model-api/0.1.1/
> Add project description on pypi

- model_api/cpp/tilers/src/detection.cpp
- model_api/cpp/tilers/src/instance_segmentation.cpp
Check ov::Tensors before accessing their methods
> Fix tilers failing without xai

- model_api/cpp/models/include/models/classification_model.h
- model_api/cpp/models/include/models/results.h
- model_api/cpp/models/src/classification_model.cpp
- model_api/python/openvino/model_api/models/classification.py
- model_api/python/openvino/model_api/models/utils.py
- tests/python/accuracy/public_scope.json
In C++ implementation raw scores are not required at the moment
> Add probs output to satisfy Geti's research framework reqs

- model_api/cpp/models/src/classification_model.cpp
- model_api/python/openvino/model_api/models/anomaly.py
- model_api/python/openvino/model_api/models/classification.py
- model_api/python/openvino/model_api/tilers/__init__.py
- Fix probs vertor in cls cpp wrapper
- Expose abstract tiler in tilers module
- Fix double activation of multiclass cls raw scores
> Minor fixes

- model_api/cpp/models/include/models/results.h
- model_api/cpp/models/src/segmentation_model.cpp
- model_api/python/openvino/model_api/models/segmentation.py
- model_api/python/openvino/model_api/models/utils.py
- tests/python/accuracy/public_scope.json
> Add saliency_map for Semantic segmentation

- model_api/cpp/models/src/classification_model.cpp
- model_api/python/openvino/model_api/models/classification.py
- tests/python/accuracy/prepare_data.py
- tests/python/accuracy/public_scope.json
- tests/python/accuracy/test_accuracy.py
Softmax node now is searched in the output nodes only
> Fix cls transformers inference

- model_api/python/openvino/model_api/tilers/instance_segmentation.py
Fixing cv2.resize in saliency map merge for isegm.
> Fix saliency map merge for instance_segmentation

- model_api/python/setup.py
> Version up

- model_api/python/openvino/model_api/models/image_model.py
- model_api/python/openvino/model_api/models/ssd.py
Ticket 123278
Currently there's no OMZ model adapted for model_api which would trigger such case, thus I'm not adding a test.
> Fix width and height extraction

- model_api/cpp/models/include/models/results.h
- model_api/cpp/models/src/anomaly_model.cpp
- model_api/python/openvino/model_api/models/anomaly.py
- model_api/python/openvino/model_api/models/utils.py
- tests/python/accuracy/public_scope.json
- Fixes https://jira.devtools.intel.com/browse/CVS-127165
> Return anomaly maps in range 0-255

- .github/workflows/test_precommit.yml
- model_api/cpp/utils/include/utils/common.hpp
- model_api/python/openvino/model_api/adapters/openvino_adapter.py
- tests/cpp/precommit/prepare_data.py
- tests/cpp/precommit/public_scope.json
- tests/python/precommit/test_load.py
When loading models one can use indices instead of names
> Add support of models converted by OVC

- model_api/python/requirements.txt
OMZ is going to remove models and openvino namespace in 24.0
> Pin omz_tools to release

- model_api/cpp/models/src/anomaly_model.cpp
- model_api/python/openvino/model_api/models/anomaly.py
- model_api/python/openvino/model_api/models/utils.py
- tests/python/accuracy/public_scope.json
> 🐞 Bugfix: Incorrect Normal score computation

- model_api/python/openvino/model_api/models/classification.py
Only Python part fixed. #TODO CPP part
Reorder saliency maps for h-cls according to labels in .xml meta
Fixes # CVS-132079
> Reorder saliency maps for h-cls according to labels in .xml meta

- model_api/cpp/models/src/image_model.cpp
Use a common function to read `reverse_input_channels`
Previous implementation throws a error on True/False strings
> Fix reverse_input_channels reading in cpp

- model_api/cpp/models/src/instance_segmentation.cpp
> Filter invalid iseg boxes in cpp to match python

- model_api/cpp/models/include/models/anomaly_model.h
- model_api/cpp/models/include/models/classification_model.h
- model_api/cpp/models/include/models/detection_model.h
- model_api/cpp/models/include/models/image_model.h
- model_api/cpp/models/include/models/instance_segmentation.h
- model_api/cpp/models/include/models/model_base.h
- model_api/cpp/models/include/models/segmentation_model.h
- model_api/cpp/models/src/anomaly_model.cpp
- model_api/cpp/models/src/classification_model.cpp
- model_api/cpp/models/src/detection_model.cpp
- model_api/cpp/models/src/image_model.cpp
- model_api/cpp/models/src/instance_segmentation.cpp
- model_api/cpp/models/src/model_base.cpp
- model_api/cpp/models/src/segmentation_model.cpp
- model_api/cpp/tilers/include/tilers/instance_segmentation.h
- model_api/cpp/tilers/src/instance_segmentation.cpp
- model_api/python/model_api/adapters/openvino_adapter.py
- model_api/python/requirements.txt
> Add configuration overriding to cpp adapters when using inference adapter

- model_api/python/model_api/adapters/utils.py
- tests/python/precommit/test_utils.py
Fixes https://github.com/openvinotoolkit/model_api/issues/167
Example source:
```python
import torch
import tempfile
import numpy as np
import matplotlib.pyplot as plt
import openvino
from openvino.model_api.adapters import OpenvinoAdapter, create_core
from openvino.model_api.adapters.utils import resize_image_with_aspect_ocv
from openvino.preprocess import PrePostProcessor
class DummyModel(torch.nn.Module):
def forward(self, inputs):
return inputs
model = DummyModel()
with tempfile.TemporaryDirectory() as tmpdirname:
onnx_path = tmpdirname + "/dummy.onnx"
ov_path = tmpdirname + "/dummy.xml"
torch.onnx.export(
model,
(torch.zeros(1, 3, 1024, 1024, dtype=torch.float32)),
open(onnx_path, "wb"),
input_names=["inputs"],
output_names=["outputs"])
ov_model = openvino.convert_model(onnx_path) …
```
> Fix `resize_image_ocv` for `fit_to_window`

- model_api/python/model_api/tilers/detection.py
- model_api/python/model_api/tilers/instance_segmentation.py
- model_api/python/model_api/tilers/tiler.py
Provide an option to include the full image on the tile.
> Make tile with full img optional

- model_api/cpp/tilers/include/tilers/tiler_base.h
- model_api/cpp/tilers/src/detection.cpp
- model_api/cpp/tilers/src/instance_segmentation.cpp
- model_api/cpp/tilers/src/tiler_base.cpp
- model_api/python/model_api/tilers/instance_segmentation.py
- model_api/python/model_api/tilers/tiler.py
This PR ports https://github.com/openvinotoolkit/model_api/pull/174 to cpp
> Add option to disable full-image tile in cpp

- docs/model-configuration.md
- model_api/python/README.md
- model_api/python/docs/ActionClassification.md
- model_api/python/model_api/adapters/utils.py
- model_api/python/model_api/models/__init__.py
- model_api/python/model_api/models/action_classification.py
- tests/cpp/accuracy/test_accuracy.cpp
- tests/python/accuracy/prepare_data.py
- tests/python/accuracy/public_scope.json
- tests/python/accuracy/test_accuracy.py
Add ActionClassificationModel which is a wrapper class for action classification model.
> Add action classification class

- .github/workflows/test_accuracy.yml
- .github/workflows/test_precommit.yml
Update is required according to Intel safety policies
> Update permissions for workflows

- model_api/cpp/models/include/models/classification_model.h
- model_api/cpp/models/src/classification_model.cpp
- model_api/python/model_api/models/anomaly.py
- model_api/python/model_api/models/classification.py
- tests/python/accuracy/public_scope.json
This port is supposed to fix the discrepancy vs hierarchical classification predictions generated by OTX SDK v1.4
> Port probabilistic label resolver from OTX SDK

- README.md
- docs/model-configuration.md
- model_api/python/model_api/models/instance_segmentation.py
- model_api/python/model_api/models/visual_prompting.py
- Docs
- MRCNN empty labels handling
- VPT non-existing index
> Minor bugfixes

- model_api/python/model_api/models/instance_segmentation.py
Fixes MRCNN fix label index out of bound
> Fix MRCNN label index out of bound

- model_api/cpp/models/src/instance_segmentation.cpp
> Skip wrong labels in IS MRCNN wrapper

- .github/workflows/test_precommit.yml
- model_api/python/pyproject.toml
- tests/python/accuracy/public_scope.json
- 3.8 is EOL soon
- OV 2024.4 won't support 3.8
- MacOS 12 EOL is this November
> Del python 3.8 support

- model_api/cpp/models/include/models/segmentation_model.h
- model_api/cpp/models/src/segmentation_model.cpp
- model_api/cpp/tilers/include/tilers/semantic_segmentation.h
- model_api/cpp/tilers/src/semantic_segmentation.cpp
- model_api/python/model_api/models/segmentation.py
- model_api/python/model_api/tilers/__init__.py
- model_api/python/model_api/tilers/instance_segmentation.py
- model_api/python/model_api/tilers/semantic_segmentation.py
- tests/cpp/accuracy/test_accuracy.cpp
- tests/python/accuracy/prepare_data.py
- tests/python/accuracy/public_scope.json
- tests/python/accuracy/test_accuracy.py
Adds semantic segmentation tiler and tests
> Tiling for semantic segmentation

- .github/workflows/test_accuracy.yml
- .github/workflows/test_precommit.yml
Add a merge group for the master branch
> Add changes required to enable merge queue

- docs/source/cpp/models/anomaly_model.md
- docs/source/python/models/anomaly.md
- docs/source/python/models/classification.md
- docs/source/python/models/segmentation.md
- model_api/python/model_api/models/anomaly.py
- model_api/python/model_api/models/classification.py
- model_api/python/model_api/models/segmentation.py
- CVS-156318
- Add documentation for Anomaly, Classification, and Segmentation models
> 📋 Add documentation for Anomaly, Classification, and Segmentation

- model_api/python/model_api/adapters/inference_adapter.py
- model_api/python/model_api/adapters/onnx_adapter.py
- model_api/python/model_api/adapters/openvino_adapter.py
- model_api/python/model_api/adapters/ovms_adapter.py
- model_api/python/model_api/adapters/utils.py
- model_api/python/model_api/models/anomaly.py
- model_api/python/model_api/models/classification.py
- model_api/python/model_api/models/image_model.py
- model_api/python/model_api/models/instance_segmentation.py
- model_api/python/model_api/models/model.py
- model_api/python/model_api/models/sam_models.py
- model_api/python/model_api/models/segmentation.py
- model_api/python/model_api/models/types.py
- model_api/python/model_api/models/utils.py
- model_api/python/pyproject.toml
- Enables type checking section rule
- Annotate the majority of modules
> Type annotation

- model_api/cpp/tilers/include/tilers/detection.h
- model_api/cpp/tilers/include/tilers/instance_segmentation.h
- model_api/cpp/tilers/include/tilers/semantic_segmentation.h
- model_api/cpp/tilers/src/detection.cpp
- model_api/cpp/tilers/src/instance_segmentation.cpp
- model_api/cpp/tilers/src/semantic_segmentation.cpp
Previously, the mode forwarding was just missing.
> Expose inference mode to all tilers

- .github/labeler.yml
> Fix PR labeler

- .github/workflows/test_accuracy.yml
- src/cpp/models/include/models/results.h
That's a requirement from the Geti's side
> Run accuracy tests with py 3.12

- src/cpp/models/include/models/keypoint_detection.h
- src/cpp/models/include/models/results.h
- src/cpp/models/src/keypoint_detection.cpp
- src/python/model_api/models/keypoint_detection.py
- src/python/model_api/models/result/keypoint.py
- tests/python/accuracy/public_scope.json
- Softmax is added to cpp and python
- Kp result repr now respects scores
> Add softmax to keypoints postprocessing

- src/python/pyproject.toml
Bump a higher-level digit to reflect API changes
> Bump version to 0.3.0

- .github/workflows/publish.yaml
- src/cpp/models/include/models/results.h
Regexp didn't fit to long tags, such as `0.3.0.1`
> Fix pypi publishing

- .github/workflows/publish.yaml
- src/python/model_api/adapters/openvino_adapter.py
- src/python/pyproject.toml
Delete OMZ downloader from python InferenceAdapter
> Finally cleanup OMZ leftovers

- .github/workflows/docs.yml
Ubuntu 20.04 is deprecated, the runner can not be started
> Update ubuntu version in gha docs runner

- src/cpp/include/tasks/detection/ssd.h
- src/cpp/include/tasks/instance_segmentation.h
- src/cpp/include/utils/config.h
- src/cpp/include/utils/preprocessing.h
- src/cpp/src/tasks/anomaly.cpp
- src/cpp/src/tasks/classification.cpp
- src/cpp/src/tasks/detection/ssd.cpp
- src/cpp/src/tasks/instance_segmentation.cpp
- src/cpp/src/tasks/semantic_segmentation.cpp
- src/cpp/src/utils/preprocessing.cpp
- tests/python/accuracy/public_scope.json
- MaskRCNN results under resize_letterbox are the same as before the refactoring
- Just in case other preprocessing params are considered during serialization for other models too
> Restore resize modes for MaskRCNN

- docs/source/conf.py
- pyproject.toml
`/docs` directory is now scanned by code quality tools.
Fixes #371
> chore(ci): enable checking of docs

- .github/workflows/docs.yml
- docs/Makefile
> chore: fix docs building
