- model_api/cpp/models/include/models/classification_model.h
- model_api/cpp/models/src/classification_model.cpp
- model_api/python/openvino/model_api/models/classification.py
- tests/cpp/accuracy/test_accuracy.cpp
It turns out we didn't actually test C++ deserialization.
Enabling it revealed that Classification is missaligned.
Updated Python version. That requires ov.Model modification which prohibits OVMS serving case,
but it seems we already lost this feature after we added inference_adapter.embed_preprocessing to ImageModel.
Merge after https://github.com/openvinotoolkit/model_api/pull/52
> Fix cpp deserialize tests

- model_api/cpp/models/src/classification_model.cpp
For get_rt_info() there's already a parser accepting OpenVINO bool representation and True/False. So we can allow OpenVINO to store bools as it wishes.
> Remove bool workaround for set_rt_info()

- model_api/cpp/models/src/instance_segmentation.cpp
- model_api/python/openvino/model_api/models/instance_segmentation.py
- model_api/python/openvino/model_api/tilers/__init__.py
- model_api/python/openvino/model_api/tilers/detection.py
- model_api/python/openvino/model_api/tilers/instance_segmentation.py
- model_api/python/openvino/model_api/tilers/tiler.py
- tests/cpp/accuracy/test_accuracy.cpp
- tests/python/accuracy/prepare_data.py
- tests/python/accuracy/public_scope.json
- tests/python/accuracy/test_accuracy.py
> Add python version of tilers

- model_api/cpp/utils/src/image_utils.cpp
- model_api/python/openvino/model_api/adapters/utils.py
- model_api/python/openvino/model_api/models/detection_model.py
Close https://github.com/openvinotoolkit/model_api/issues/99
The implementation was incorrect. It performed scales based interpolation instead if sizes. Padding was missing. Now it is aligned with C++.
> Fix `fit_to_window` Python embed_preprocessing()

- model_api/cpp/models/src/model_base.cpp
Throws were missing from runtime errors.
This was obfuscated an issue when using inference adapter
> Add Throws to the created runtime_errors

- model_api/cpp/tilers/src/detection.cpp
- model_api/python/openvino/model_api/tilers/detection.py
If detection tiler receives an image << tile size, the size of the merged saliency map is zero, because tiler supposes image >> tile size.
> Replicate changes from https://github.com/openvinotoolkit/training_extensions/pull/2452

- .github/workflows/test_precommit.yml
Apply TODO
Reduce the number of macos runs because it seems openvinotoolkit runners are busy.
> Update macos tests

- model_api/cpp/models/src/anomaly_model.cpp
- model_api/python/openvino/model_api/models/anomaly.py
- model_api/python/openvino/model_api/models/utils.py
Only for detection and segmentation tasks the anomaly task thresholds the anomaly map.
For classification this causes a cv error since pred_mask is not set.
> Fix Anomaly Classification

- model_api/cpp/models/src/classification_model.cpp
- model_api/python/openvino/model_api/models/classification.py
- tests/python/accuracy/public_scope.json
- tests/python/accuracy/test_accuracy.py
model_info is forwarded to the new model in addOrFindSoftmaxAndTopkOutputs
> Fix missing model_info when embedding softmax

- model_api/cpp/models/src/segmentation_model.cpp
Using SegmentationModel with OpenVINO Model Server adapter caused ov::merge exception.
The reason is the order of the outputs.
This PR makes sure, that `feature_vector` is not used in postprocess() function.
> SegmentationModel - get proper output in postprocess()

- model_api/python/openvino/model_api/adapters/openvino_adapter.py
Accessing the output node is more correct, since the only supported by `get_tensor()` types are:
1. (self: openvino._pyopenvino.InferRequest, name: str) -> openvino._pyopenvino.Tensor
2. (self: openvino._pyopenvino.InferRequest, port: openvino._pyopenvino.ConstOutput) -> openvino._pyopenvino.Tensor
3. (self: openvino._pyopenvino.InferRequest, port: openvino._pyopenvino.Output) -> openvino._pyopenvino.Tensor
Previously, that worked because cls model replaces outputs, so avoiding a error in the constructor was enough
> Use output itself rather than index for unnamed outputs

- model_api/python/openvino/model_api/models/classification.py
Feature vector name was included into the output of `_get_non_xai_names`, which is not desired behavior and is not aligned with cpp
> Fix non-xai outputs filtering in cls models

- .github/workflows/test_precommit.yml
- README.md
- examples/python/synchronous_api/run.py
- model_api/python/openvino/model_api/adapters/openvino_adapter.py
- model_api/python/requirements.txt
- tests/cpp/precommit/public_scope.json
- tests/python/accuracy/public_scope.json
- tests/python/accuracy/test_accuracy.py
- tests/python/precommit/test_save.py
After this is merged It will be required to release model_api 0.2.0 only after openvino 2024.0 because model_api is going to import OMZ using a new namespace
> Move to newer OMZ

- model_api/cpp/models/src/classification_model.cpp
- tests/python/accuracy/prepare_data.py
- tests/python/accuracy/public_scope.json
OVMS adapter can return the names in an arbitrary order, while the cls wrapper expects logits to be at the first place.
> Don't rely on outputs order from adapter in cls wrapper

- model_api/cpp/models/src/model_base.cpp
- model_api/cpp/tilers/include/tilers/detection.h
- model_api/cpp/tilers/include/tilers/instance_segmentation.h
- model_api/cpp/tilers/include/tilers/tiler_base.h
- model_api/cpp/tilers/src/detection.cpp
- model_api/cpp/tilers/src/instance_segmentation.cpp
- model_api/cpp/tilers/src/tiler_base.cpp
- tests/cpp/accuracy/test_accuracy.cpp
- Tilers now return wrapper-specific results, instead of `ResultBase`
- Fix possible call of empty function when a custom callback was not set before batch inference
> Return task-specific result type from tilers

- model_api/cpp/tilers/src/detection.cpp
- model_api/python/model_api/tilers/detection.py
Tile merging: detection.
If only one tiled saliency map for merging, skip the calculation.
Align with OTX to pass integration tests which fail because of different size of merged tiled saliency maps.
> Skip tiled saliency map merging if only one map is available

- .github/workflows/test_accuracy.yml
- .github/workflows/test_precommit.yml
- model_api/cpp/install_dependencies.sh
- model_api/python/pyproject.toml
- tests/cpp/accuracy/CMakeLists.txt
- tests/cpp/precommit/CMakeLists.txt
Python 3.8 is EOL is 31 Oct 2024: https://endoflife.date/python
> Drop python 3.8 support

- .github/workflows/test_precommit.yml
- tests/cpp/accuracy/CMakeLists.txt
- tests/cpp/precommit/CMakeLists.txt
- Restore pip cache
- Del forcing cpp14 for win tests
> Revert changes required to pass CI after python version change

- model_api/python/model_api/models/keypoint_detection.py
- model_api/python/model_api/models/model.py
Batch inference emulation is done by enqueuing batch items for async inference.
That design allows to avoid usage of AsyncPipeline, simplifying batch processing for end users.
However, if obtaining every batch element is somehow expensive, AsyncPipeline allows to squeeze more performance by running infer requests in parallel to preparation of the next batch elements.
> [python] Add batch inference emulation 

- model_api/cpp/models/include/models/keypoint_detection.h
- model_api/cpp/models/include/models/results.h
- model_api/cpp/models/include/models/segmentation_model.h
- model_api/cpp/models/src/detection_model_ssd.cpp
- model_api/cpp/models/src/detection_model_yolo.cpp
- model_api/cpp/models/src/instance_segmentation.cpp
- model_api/cpp/models/src/keypoint_detection.cpp
- model_api/cpp/models/src/segmentation_model.cpp
- model_api/python/model_api/models/keypoint_detection.py
- tests/cpp/accuracy/test_accuracy.cpp
- Wrapper for a crop model only
- Minor fixes in cpp preprocessing
- Simplify python kp postproc
- Compliance test vs python crop model wrapper
> [cpp] Add keypoint detection wrapper

- model_api/python/model_api/models/classification.py
3rd party and preprocessed models should be discriminated in cls wrapper
> [python] Fix classification usage via OVMS

- model_api/cpp/models/include/models/classification_model.h
- model_api/cpp/models/src/classification_model.cpp
- model_api/python/model_api/models/classification.py
Previously, greedy resolver was adding labels from multilabel section without checking if it's actually predicted.
> Fix a corner case in h-cls greedy resolver

- model_api/cpp/models/src/detection_model_ssd.cpp
- model_api/python/model_api/models/detection_model.py
- model_api/python/model_api/models/ssd.py
- Filter now can handle +-inf values
- Boxes with area < 1 pix are not considered, like in iseg wrapper
> Add detection filtering for SSD wrapper

- model_api/cpp/adapters/include/adapters/inference_adapter.h
- model_api/cpp/adapters/include/adapters/openvino_adapter.h
- model_api/cpp/adapters/src/openvino_adapter.cpp
This is required to allow no-copy inference with Model API within Mediapipe graphs.
Use OVMS C-API with set output to avoid copy in OVMSModelAPIAdapter.
Ticket: CVS-155477
Related changes:
https://github.com/openvinotoolkit/model_server/pull/2763
https://github.com/openvinotoolkit/mediapipe/pull/92
> Adjust cpp inference adapters for OVMS

- model_api/python/model_api/models/anomaly.py
- model_api/python/model_api/models/classification.py
- model_api/python/model_api/models/image_model.py
- model_api/python/model_api/models/instance_segmentation.py
- model_api/python/model_api/models/sam_models.py
- model_api/python/model_api/models/segmentation.py
- model_api/python/model_api/models/utils.py
- Add typing to some of the files.
> Add Typing Part 1

- model_api/cpp/models/include/models/results.h
Fixes CVS-155311
This PR fixes corner case, where detected contours were 0:
`Calculator::Process() for node "RotatedDetectionCalculator" failed: ; RET_CHECK failure (external/geti_calculators/inference/geti_calculator_base.h:32) false
Caught exception with message: OpenCV(4.10.0) /opt/opencv_repo/modules/imgproc/src/convhull.cpp:143: error: (-215:Assertion failed) total >= 0 && (depth == CV_32F || depth == CV_32S) in function 'convexHull'
`
> CVS-156311 fix corner case in contours detection

- .github/workflows/test_precommit.yml
- model_api/python/model_api/adapters/inference_adapter.py
- model_api/python/model_api/adapters/onnx_adapter.py
- model_api/python/model_api/adapters/openvino_adapter.py
- model_api/python/model_api/adapters/ovms_adapter.py
- model_api/python/model_api/models/model.py
- tests/cpp/precommit/prepare_data.py
- tests/cpp/precommit/public_scope.json
- tests/python/funtional/__init__.py
- tests/python/funtional/conftest.py
- tests/python/funtional/test_load.py
- tests/python/funtional/test_save.py
- Removes OV-specific references from the abstract Model
> Refactor model saving

- .github/labeler.yml
- .github/workflows/pr-labeler.yml
Adds a basic labeler that can be extended further
> Add PR labeler

- model_api/python/model_api/models/action_classification.py
- model_api/python/model_api/models/classification.py
- model_api/python/model_api/models/result_types/__init__.py
- model_api/python/model_api/models/result_types/classification.py
- tests/python/unit/results/test_cls_result.py
Tuple-like behavior is preserved to avoid client code changes:
```python
predictions: ClassificationResult
for label_idx, label_name, prob in predictions.top_labels:
...
```
> Replace unnamed tuple in cls result with a label object

- model_api/python/model_api/adapters/inference_adapter.py
- model_api/python/model_api/adapters/onnx_adapter.py
- model_api/python/model_api/adapters/openvino_adapter.py
- model_api/python/model_api/adapters/ovms_adapter.py
- model_api/python/model_api/models/image_model.py
- model_api/python/model_api/models/model.py
Update the inline docs for adapter and model.
> Update core API docs: Adapter and Model

- model_api/python/model_api/adapters/onnx_adapter.py
- model_api/python/model_api/adapters/ovms_adapter.py
- model_api/python/model_api/models/anomaly.py
- model_api/python/model_api/models/classification.py
- model_api/python/model_api/models/instance_segmentation.py
- model_api/python/model_api/models/sam_models.py
- model_api/python/model_api/models/visual_prompting.py
- model_api/python/model_api/tilers/instance_segmentation.py
- model_api/python/model_api/tilers/tiler.py
- model_api/python/pyproject.toml
> 🧹 Enable more pre-commit rules

- .github/workflows/test_precommit.yml
- model_api/cpp/CMakeLists.txt
OV installation process implies downloading a .deb package or adding a PPA. This PR relaxes this requirement a bit by utilizing recently introduced in OV mechanism. Now, we can use binaries from OV python package, which is easy to install.
> Enable linking against OV python package

- model_api/python/model_api/visualizer/__init__.py
- model_api/python/model_api/visualizer/primitive.py
- tests/python/unit/visualizer/test_primitive.py
- Add bounding box primitive.
- Accepts label as an optional parameter
> Add bounding box primitive

- src/python/model_api/visualizer/__init__.py
- src/python/model_api/visualizer/primitive/__init__.py
- src/python/model_api/visualizer/primitive/bounding_box.py
- src/python/model_api/visualizer/primitive/overlay.py
- src/python/model_api/visualizer/primitive/polygon.py
- src/python/model_api/visualizer/primitive/primitive.py
- tests/python/unit/visualizer/test_primitive.py
- Add Polygon primitive to the visualizer
> Add Polygon Primitive

- src/python/model_api/visualizer/__init__.py
- src/python/model_api/visualizer/layout/flatten.py
- src/python/model_api/visualizer/layout/hstack.py
- src/python/model_api/visualizer/primitive/__init__.py
- src/python/model_api/visualizer/primitive/label.py
- src/python/model_api/visualizer/scene/scene.py
- tests/python/unit/visualizer/test_primitive.py
```python
label1 = Label(label="Label 1")
label2 = Label(label="Label 2", bg_color="red")
label3 = Label(label="Label 3", bg_color="blue")
scene = MockScene(image, label=[label1, label2, label3], layout=Flatten(Label))
scene.save("scene_flatten.jpg")
scene = MockScene(image, label=[label1, label2, label3], layout=HStack(Label))
scene.save("scene_hstack.jpg")
```
> Add Label Primitive

- src/python/model_api/visualizer/layout/flatten.py
- src/python/model_api/visualizer/primitive/label.py
- src/python/model_api/visualizer/scene/anomaly.py
- src/python/model_api/visualizer/scene/classification.py
- src/python/model_api/visualizer/scene/detection.py
- src/python/model_api/visualizer/scene/scene.py
- src/python/model_api/visualizer/visualizer.py
- tests/python/unit/visualizer/test_scene.py
- Add Anomaly Scene
```python
image = Image.open("./data/coco128/images/train2017/000000000074.jpg")
image = image.resize((255, 255))  # Ideally this should be within visualization
heatmap = np.zeros(image.size, dtype=np.uint8)
heatmap[64:96, 64:96] = 255
mask = np.zeros(image.size, dtype=np.uint8)
mask[32:96, 32:96] = 255
mask[40:80, 0:128] = 255
anomaly_result = AnomalyResult(
anomaly_map=heatmap,
pred_boxes=np.array([[0, 0, 128, 128], [32, 32, 96, 96]]),
pred_label="Anomaly",
pred_mask=mask,
pred_score=0.85,
)
visualizer = Visualizer()
visualizer.save(image, anomaly_result, "anomaly_result.jpg")
```
```python
image = Image.open("./data/coco128/images/train2017/000000000074.jpg")
image_array = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)
padim = AnomalyDetection.create_model( …
```
> Add Anomaly scene

- src/python/model_api/models/result/detection.py
- src/python/model_api/visualizer/layout/hstack.py
- src/python/model_api/visualizer/primitive/overlay.py
- src/python/model_api/visualizer/scene/classification.py
- src/python/model_api/visualizer/scene/detection.py
- tests/python/unit/visualizer/test_scene.py
- Add Classification Scene
- Add Detection Scene
- Merge after https://github.com/openvinotoolkit/model_api/pull/257
```python
image = Image.open("./data/coco128/images/train2017/000000000074.jpg")
image_array = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)
cls_model = ClassificationModel.create_model(
"./data/otx_models/mlc_mobilenetv3_large_voc.xml"
)
predictions = cls_model(image_array)
visualizer = Visualizer()
visualizer.save(image, predictions, "visualizer_output.jpg")
```
```python
image = Image.open("./data/coco128/images/train2017/000000000257.jpg")
image_array = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)
det_model = DetectionModel.create_model(
"./data/otx_models/detection_model_with_xai_head.xml"
)
predictions = det_model(image_array)
visualizer = Visualizer() …
```
> Add Classification And Detection Scene

- model_api/cpp/models/include/models/keypoint_detection.h
- model_api/cpp/models/src/keypoint_detection.cpp
- model_api/python/model_api/models/keypoint_detection.py
Softmax was missing in postprocessing.
> [0.2.5.1] Add softmax to keypoint model wrapper

- .github/workflows/test_accuracy.yml
- .github/workflows/test_precommit.yml
- src/cpp/CMakeLists.txt
- src/cpp/install_dependencies.sh
- src/cpp/py_bindings/CMakeLists.txt
- src/python/model_api/adapters/openvino_adapter.py
- src/python/model_api/adapters/utils.py
- src/python/model_api/models/classification.py
- src/python/model_api/visualizer/visualizer.py
- src/python/pyproject.toml
- tests/cpp/accuracy/CMakeLists.txt
- tests/cpp/accuracy/test_accuracy.cpp
- tests/cpp/cmake/common.cmake
- tests/cpp/precommit/CMakeLists.txt
- tests/cpp/precommit/prepare_data.py
- tests/cpp/precommit/public_scope.json
- tests/cpp/precommit/test_model_config.cpp
- tests/python/accuracy/public_scope.json
- tests/python/functional/test_save.py
- tests/python/unit/test_utils.py
- Bump OV version, fix related warnings
- Add support of ndarrays as an input to Visualizer
- Fix accuracy tests
- Don't test on OMZ models
> Support OV 2025.0

- src/python/model_api/models/result/detection.py
- src/python/pyproject.toml
- tests/python/unit/results/test_det_result.py
Old behavior (before refactoring) is restored now.
Some detectors may return floats and it's hard to change for already generated OV models
> Convert labels to int in det result

- .github/workflows/pre_commit.yml
- .github/workflows/test_precommit.yml
- .pre-commit-config.yaml
- src/python/model_api/models/ssd.py
- src/python/pyproject.toml
- Incorrect order of input args
- Ubuntu 20.04 image is deprecated in GHA
> Fix multiple output ssd parser

- model_api/python/model_api/models/keypoint_detection.py
- model_api/python/pyproject.toml
- tests/python/accuracy/public_scope.json
> [0.2.5] Fix keypoint detection inference

- src/cpp/models/src/keypoint_detection.cpp
- src/python/model_api/models/keypoint_detection.py
- tests/cpp/accuracy/test_accuracy.cpp
- tests/python/accuracy/public_scope.json
- Add support of 2 fit to window resize modes
- Re-consider how kp scores are calculated: now visibility score is computed instead
Issues: OV 2025. gives incorrect result when running inference on raw KP model in cpp. We don't use raw models in cpp directly. To be double-checked after OV 2025.1 release
> Support all resize types in kp model

- src/cpp/CMakeLists.txt
- tests/cpp/accuracy/CMakeLists.txt
- tests/cpp/cmake/common.cmake
- tests/cpp/precommit/CMakeLists.txt
json lib has outdated cmake min version (<3.5) in the latest release -> switching a git commit containing a fix
See https://github.com/nlohmann/json/pull/4709
> Fix cmake deprecation failure coming from 3rd party

- .github/workflows/docs.yml
Redirect to the latest docs folder was missing:
it hasn't been created initially and `git commit -a` didn't add it later
> Add missing redirect to the main gh page

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- CONTRIBUTING.md
- README.md
> Add a contribution guide and issue templates

- src/cpp/include/adapters/inference_adapter.h
- src/cpp/include/adapters/openvino_adapter.h
- src/cpp/src/adapters/openvino_adapter.cpp
- src/cpp/src/tasks/anomaly.cpp
- src/cpp/src/tasks/classification.cpp
- src/cpp/src/tasks/detection.cpp
- src/cpp/src/tasks/detection/ssd.cpp
- src/cpp/src/tasks/instance_segmentation.cpp
- src/cpp/src/tasks/semantic_segmentation.cpp
To support ONNX models with OV adapter, we need to hide actual OV model from the wrapper and handle it in the adapter only.
> Hide ov::Model from wrappers

- model_api/python/model_api/models/types.py
- model_api/python/pyproject.toml
> Add a workaround to avoid unexpected conversion to int

- src/cpp/models/include/models/segmentation_model.h
- src/cpp/models/src/segmentation_model.cpp
- src/python/model_api/models/segmentation.py
Searching for holes in contours can now be disabled
> Add a simplified mode for contours processing

- README.md
- src/cpp/utils/src/image_utils.cpp
- tests/python/accuracy/prepare_data.py
Reference for resize graph: https://github.com/open-edge-platform/model_api/blob/master/src/python/model_api/adapters/utils.py#L329-L336
> Minor fixes

- src/model_api/models/anomaly.py
- src/model_api/models/image_model.py
- src/model_api/models/model.py
- padim
- stfpm
- uflow
anomaly_map min/max: 149/255
anomaly_map mean: 212.12
anomaly_map std: 25.56
anomaly_map shape: (1371, 2048)
anomaly_map dtype: uint8
anomaly_map min/max: 148/255
anomaly_map mean: 219.27
anomaly_map std: 24.39
anomaly_map shape: (1371, 2048)
anomaly_map dtype: uint8
anomaly_map min/max: 119/255
anomaly_map mean: 230.04
anomaly_map std: 22.99
anomaly_map shape: (1371, 2048)
anomaly_map dtype: uint8
anomaly_map min/max: 120/255
anomaly_map mean: 236.65
anomaly_map std: 20.05
anomaly_map shape: (1371, 2048)
anomaly_map dtype: uint8
anomaly_map min/max: 191/191
anomaly_map mean: 191.00
anomaly_map std: 0.00
anomaly_map shape: (1371, 2048)
anomaly_map dtype: uint8
anomaly_map min/max: 184/191
anomaly_map mean: 190.96
anomaly_map std: 0.38
anomaly_map shape: (1371, …
> feat: add support for exported models from anomalib

- .github/dependabot.yml
Dependabot was configured to create pr titiles starting with `chore(deps)` as proposed by Conventional Commits
Fixes #367 367
> chore(ci): configure dependabot to use semanctic commits

- src/model_api/adapters/inference_adapter.py
- src/model_api/adapters/onnx_adapter.py
- src/model_api/adapters/openvino_adapter.py
- src/model_api/adapters/ovms_adapter.py
- src/model_api/adapters/utils.py
- src/model_api/models/classification.py
- src/model_api/models/image_model.py
- src/model_api/models/model.py
- src/model_api/models/sam_models.py
- src/model_api/models/segmentation.py
- src/model_api/models/types.py
- src/model_api/models/utils.py
- src/model_api/models/visual_prompting.py
- src/model_api/visualizer/visualizer.py
Our code includes `from __future__ import annotations` statements, some of those were marked as to be removed when moved to Python 3.10 - it was believed at that time that such imports will not be needed anymore.
`annotations` are still needed - as mentined in https://docs.python.org/3/library/__future__.html#id2 inclusion of that behavior was  not included in Python 3.10 or 3.11, and finally posponed indefinitely.
In effect comments advising removal of imports were removed.
Fixes #363
> chore(comments): remove comment in annotations import

- examples/asynchronous_api/run.py
- examples/serving_api/run.py
- examples/synchronous_api/run.py
- examples/visual_prompting/run.py
- examples/zsl_visual_prompting/run.py
- pyproject.toml
- tests/accuracy/conftest.py
- tests/accuracy/prepare_data.py
- tests/accuracy/test_YOLOv8.py
- tests/accuracy/test_accuracy.py
- tests/functional/test_save.py
- tests/precommit/prepare_data.py
- tests/unit/results/test_cls_result.py
- tests/unit/results/test_det_result.py
- tests/unit/results/test_sseg_result.py
- tests/unit/test_utils.py
- tests/unit/visualizer/test_primitive.py
- tests/unit/visualizer/test_scene.py
> chore: enable checking of styles in examples, tests

- tests/accuracy/prepare_data.py
- tests/accuracy/public_scope.json
- tests/precommit/prepare_data.py
Tests (pre-commit and accuracy) are using models downloaded from public repository.
This PR changes the location used from `storage.openvinotoolkit.org/repositories/model_api` to new one `storage.geti.intel.com/geti_predict` that will be used as a future storage place for Model API.
Fixes #385
> test: models from geti_predict used in tests

- tests/accuracy/conftest.py
- tests/accuracy/test_accuracy.py
OpenvinoAdapter allows to select the device inference will be executed on.
For Accuracy tests it was hardcoded to `"CPU"`, now it's configurable by `--device` argument (with default value of `"CPU"`).
This allows to run Accuracy tests on iGPU or NPU with a simple command line command.
Fixes #398
> test: ability to select device used by OpenvinoAdapter

- tests/accuracy/conftest.py
- tests/accuracy/test_accuracy.py
Adding `--results-dir` option to `test_accuracy.py` will save images with inference results in specified directory.
Fixes #409
> tests: option to save test results as images
